name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@1.0
        with:
          xcode-version: latest
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        run: swift test --enable-test-discovery --sanitize=thread

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - swift:5.3-focal
          - swift:5.3-bionic
          - swift:5.3-xenial
          - swift:5.3-centos8
          - swift:5.3-amazonlinux2
    name: "Linux (Swift ${{ matrix.image }})"
    container: ${{ matrix.image }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        timeout-minutes: 10
        run: swift test --enable-test-discovery --sanitize=thread
