name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - swift:5.4-focal
          - swift:5.4-bionic
          - swift:5.4-xenial
          - swift:5.4-centos8
          - swift:5.4-amazonlinux2
    name: "Linux (Swift ${{ matrix.image }})"
    container: ${{ matrix.image }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        timeout-minutes: 10
        run: swift test --sanitize=thread
